{
 "title": "Ubuntu Server Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ubuntu Server Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", instance=\"localhost:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{job=\"node\",instance=\"localhost:9100\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (\r\n  node_memory_MemAvailable_bytes{job=\"node\",instance=\"localhost:9100\"}\r\n  /\r\n  node_memory_MemTotal_bytes{job=\"node\",instance=\"localhost:9100\"}\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  1 -\r\n  node_filesystem_avail_bytes{\r\n    job=\"node\",\r\n    instance=\"localhost:9100\",\r\n    mountpoint=\"/\"\r\n  }\r\n  /\r\n  node_filesystem_size_bytes{\r\n    job=\"node\",\r\n    instance=\"localhost:9100\",\r\n    mountpoint=\"/\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}